.gitignore
README.md
pom.xml

Signed-off-by: Geoffroy Jamgotchian <geoffroy.jamgotchian@rte-france.com>
No
feature
Migrate to PowSyBl dependencies 1.3.0

Migrate to PowSyBl dependencies 1.3.0

---

pom.xml

**What is the current behavior?** *(You can also link to an open issue here)*

Prepare release v1.0.0

---

pom.xml

Signed-off-by: Geoffroy Jamgotchian <geoffroy.jamgotchian@rte-france.com>
No
Technical debt
**What is the current behavior?** *(You can also link to an open issue here)*
SpringBoot 2.6.6
SpringBoot 2.7.3
(if any of the questions/checkboxes don't apply, …

SpringBoot 2.7.3

---

pom.xml

Prepare release 110

---

pom.xml

Signed-off-by: Geoffroy Jamgotchian <geoffroy.jamgotchian@rte-france.com>
No
Feature
**What is the current behavior?** *(You can also link to an open issue here)*
We are based on PowSyBl dependencies 1.3.0
We are based on PowSyBl dependencies 2022.0.0
(if …

Upgrade to PowSyBl dependencies 2022.0.0

---

pom.xml

No
Release
**What is the current behavior?** *(You can also link to an open issue here)*
1.3.0-SNAPSHOT
2.1.0-SNAPSHOT

Prepare release 2.0.0

---

pom.xml

Signed-off-by: Florent MILLOT <millotflo@gmail.com>
Dependencies update

Add wiremock

---

pom.xml

No
Feature
We are based on PowSyBl 2023.0.1

Migrate to PowSyBl 2023.0.1

---

pom.xml

No
Feature
Bump 2.1.0 then 2.2.0-SNAPSHOT

Prepare release 210

---

pom.xml

springboot 3.1.2 migration

---

pom.xml

powsybl-dependencies 2023.3.1
powsybl-network-store-client 1.5.0
powsybl-case-datasource-client 1.4.0
powsybl-ws-commons 1.6.0

powsybl-dependencies 2023.3.1 & update clients versions

---

pom.xml

release 2.5.0

---

pom.xml

Prepare next release 2.6.0-SNAPSHOT

prepare next release 2.6.0-SNAPSHOT

---

pom.xml

update powsybl-dependencies 2023.3.2
update powsybl-case-datasource-client 1.5.0
update powsybl-network-store-client 1.6.0
update powsybl-ws-commons 1.7.0

update dependencies (powsybl 2023.3.2)

---

pom.xml

release 2.6.0

---

pom.xml

bump 2.7.0-SNAPSHOT

---

pom.xml

release 2.7.0

---

pom.xml

bump to v2.8.0-SNAPSHOT

---

pom.xml

upgrade to powsybl-dependencies 2024.0.3

---

pom.xml

Upgrade to network store client 1.10.0

---

pom.xml

Bump to 2.9.0

---

pom.xml

Bump to 2.10.0-SNAPSHOT

---

pom.xml

Bump to 2.12.0

---

pom.xml

Bump to 2.13.0-SNAPSHOT

---

pom.xml

Bump to v2.14.0

---

pom.xml

Bump to v2.15.0-SNAPSHOT

---

pom.xml

Bump to v2.15.0

---

pom.xml

Bump to v2.16.0-SNAPSHOT

---

pom.xml

Fix bump to v2.16.0-SNAPSHOT

---

pom.xml

Fix release 2.15.0

---

pom.xml

Fix bump 2.16.0-SNAPSHOT

---

pom.xml

upgrade powsybl dependencies to v2024.3.1

---

pom.xml

release v2.16.0

---

pom.xml

bump to v2.17.0-SNAPSHOT

---

pom.xml

Upgrade to powsybl dependencies 2024.4.0, case datasource client 1.11.0, network store client 1.21.0, ws commons 1.20.0

---

pom.xml

Bump to 2.18.0-SNAPSHOT

---

.github/workflows/maven.yml
.github/workflows/patch.yml
.github/workflows/release.yml

**Does this PR introduce a new Powsybl Action implying to be implemented in simulators or pypowsybl?**

add workflows for releases and patches

---

pom.xml

**Does this PR introduce a new Powsybl Action implying to be implemented in simulators or pypowsybl?**

Upgrade powsybl dependencies 2024.4.1, network-store 1.23.0, powsybl-ws-commons 1.22.0 versions

---

pom.xml

**Does this PR introduce a new Powsybl Action implying to be implemented in simulators or pypowsybl?**

Upgrade powsybl-ws-commons 1.23.0

---

pom.xml

Upgrade to powsybl-dependencies v2025.0.1

---

pom.xml

- powsybl-dependencies v2025.0.2
- powsybl-network-store v1.27.0
- powsybl-ws-commons v1.26.0

upgrade powsybl versions:

---

pom.xml

bump to v2.23.0-SNAPSHOT

---

pom.xml

Upgrade versions: network-store v1.27.2 + ws-commons v1.26.2

Upgrade versions: network-store v1.27.2 + ws-commons v1.26.2

---

pom.xml

Release 2.24.0
